### PR TITLE
Update documentation and add docstrings to properties

### PR DESCRIPTION
**Pull request by joogps**
Hi, @florianholzapfel! I'm just adding docstrings the new properties (since I didn't define any in my previous PR #33) and updating the documentation to use these properties.

Thank you for being so supportive and merging my changes so quickly. Because of that, my pull request on the Home Assistant repo (home-assistant/core#33829) was approved!

### CODE REVIEW

**Comment by joogps** [comment]
Also, I have a question: how did you manage to find all of the SOAP request methods? I was looking forward to implementing a `get_serial_number` function, but I couldn't figure out how to do it.

**Comment by florianholzapfel** [comment]
thank you!

**Comment by florianholzapfel** [comment]
> 
> 
> Also, I have a question: how did you manage to find all of the SOAP request methods? I was looking forward to implementing a `get_serial_number` function, but I couldn't figure out how to do it.

i just found somewhere a php snippet that included everything. i have just ported it to python in order to be used in homeassistant. the encryption stuff was reverse engineered and provided by @ngws 

as long as panasonic doesn't provide any public documentation about this, i fear you need to reverse engineer this.

**Comment by joogps** [comment]
Oh, ok! Thank you!

**Comment by joogps** [comment]
@florianholzapfel I was digging into the PHP code and found out that all available functions - as well as some of the device data - are listed in these files:

http://192.168.2.7:55000/dmr/ddd.xml

**Comment by joogps** [comment]
PR created! :)

**Pull request merged**
