### PR TITLE
Making encryption variables public

### PR DESCRIPTION
**Pull request by joogps**
Hi, @florianholzapfel!

I know you don't visit this project in a while, but here I am, making a pull request. So, I'm [updating the Panasonic Viera integration in Home Assistant](https://github.com/home-assistant/core/pull/33829) (which is something I saw you worked on - and that's pretty cool), to support encrypted connections, but their guidelines won't allow me to retrieve protected variables (`_type`, `_app_id` and `_enc_key`), so my only option was to change the library's source code.

My changes are very simple (I just added functions with `@property` decorators to make the variables public), and I hope you accept them.

:D

### CODE REVIEW

**Comment by florianholzapfel** [comment]
hi, thank you for your contribution!

**Comment by joogps** [comment]
you’re welcome! do you have an idea of when the PyPI package will be updated?

**Comment by florianholzapfel** [comment]
i have just uploaded 0.3.5 :-)

**Comment by joogps** [comment]
great! thank you so much for this :)

**Comment by florianholzapfel** [comment]
you are welcome :)

**Pull request merged**
